# Site settings
title:          Ju-eun Park
description:    "Simple pages for posting"

url:            "https://Jueun-Park.github.io"

# Author
author:
  name:         Ju-eun Park
  url:          https://jueun-park.github.io
  email:        jueun.park@skku.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title

paginate: 6 
paginate_path: "/page/:num"
